// <auto-generated />
using System;
using EFCore.ChangeTriggers.Tests.Integration.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.ChangeTriggers.ChangeEventQueries.Tests.Integration.Migrations.ChangeSourceEntity
{
    [DbContext(typeof(ChangeSourceEntityDbContext))]
    partial class ChangeSourceEntityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.ChangeTriggers.Tests.Integration.Common.Domain.ChangeSourceEntity.ChangeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangeSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Migrations"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tests"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Web API"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Console"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Public API"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Email Service"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Data Retention Service"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("EFCore.ChangeTriggers.Tests.Integration.Common.Domain.ChangeSourceEntity.ChangeSourceEntityUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestUsers", t =>
                        {
                            t.HasTrigger("ChangeTrigger");
                        });

                    b
                        .HasAnnotation("ChangeTriggers:HasChangeTrigger", true)
                        .HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "66d009cc-afdf-4fd8-9560-6e7dbe62434c"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Test User 1"
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Test User 2"
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Test User 3"
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "Test User 4"
                        });
                });

            modelBuilder.Entity("EFCore.ChangeTriggers.Tests.Integration.Common.Domain.ChangeSourceEntity.ChangeSourceEntityUserChange", b =>
                {
                    b.Property<int>("ChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChangeId"));

                    b.Property<int?>("ChangeSourceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset")
                        .HasAnnotation("ChangeTriggers:IsChangedAtColumn", true);

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OperationType")
                        .HasColumnType("int")
                        .HasColumnName("OperationTypeId")
                        .HasAnnotation("ChangeTriggers:IsOperationTypeColumn", true);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChangeId");

                    b.HasIndex("ChangeSourceId");

                    b.HasIndex("Id");

                    b.ToTable("TestUserChanges");

                    b
                        .HasAnnotation("ChangeTriggers:HasChangeSource", true)
                        .HasAnnotation("ChangeTriggers:IsChangeTable", true);
                });

            modelBuilder.Entity("EFCore.ChangeTriggers.Tests.Integration.Common.Domain.ChangeSourceEntity.ChangeSourceEntityUserChange", b =>
                {
                    b.HasOne("EFCore.ChangeTriggers.Tests.Integration.Common.Domain.ChangeSourceEntity.ChangeSource", "ChangeSource")
                        .WithMany()
                        .HasForeignKey("ChangeSourceId")
                        .HasAnnotation("ChangeTriggers:HasNoCheckConstraint", true)
                        .HasAnnotation("ChangeTriggers:IsChangeSourceColumn", true);

                    b.HasOne("EFCore.ChangeTriggers.Tests.Integration.Common.Domain.ChangeSourceEntity.ChangeSourceEntityUser", "TrackedEntity")
                        .WithMany("Changes")
                        .HasForeignKey("Id")
                        .HasAnnotation("ChangeTriggers:HasNoCheckConstraint", true)
                        .HasAnnotation("ChangeTriggers:IsTrackedEntityForeignKey", true);

                    b.Navigation("ChangeSource");

                    b.Navigation("TrackedEntity");
                });

            modelBuilder.Entity("EFCore.ChangeTriggers.Tests.Integration.Common.Domain.ChangeSourceEntity.ChangeSourceEntityUser", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
