<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Summary>An Entity Framework Core extension for storing and querying changes made to entities using SQL triggers.</Summary>
	<Description>An Entity Framework Core extension for storing and querying changes made to entities using SQL triggers.</Description>
	<PackageProjectUrl>https://github.com/codemunkie15/EFCore.ChangeTriggers</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
	
  <ItemGroup>
    <PackageVersion Update="DotNet.ReproducibleBuilds" Version="1.2.39" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
	
  <ItemGroup>
    <PackageVersion Update="MinVer" Version="6.0.0" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Update="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
