name: CI
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        
      - name: "Install dotnet-ef"
        run: dotnet tool install --global dotnet-ef

      - name: "Re-scaffold integration test migrations"
        shell: pwsh
        run: .\tests\EFCore.ChangeTriggers.SqlServer.Tests.Integration\Scripts\readd-all-migrations.ps1

      - name: Build solution
        run: dotnet build --configuration $BUILD_CONFIG
        
      - name: Run tests
        run: dotnet test --configuration $BUILD_CONFIG --no-build
