name: Publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        
      - name: "Install dotnet-ef"
        run: dotnet tool install --global dotnet-ef

      - name: "Re-scaffold integration test migrations"
        shell: pwsh
        run: .\tests\EFCore.ChangeTriggers.Tests.Integration.Common\Scripts\readd-all-migrations.ps1

      - name: Build solution
        run: dotnet build --configuration $BUILD_CONFIG

      - name: Run tests
        run: dotnet test --configuration $BUILD_CONFIG --no-build

      - name: Run pack
        run: dotnet pack --configuration $BUILD_CONFIG --no-build
        
      - name: Publish
        run: dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
