name: Publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
        
    # Install the .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    # Create the NuGet package
    - name: Run pack
      run: dotnet pack --configuration $BUILD_CONFIG
      
    # Run tests
    - name: Run tests
      run: dotnet test --configuration $BUILD_CONFIG --no-build
      
    # Publish
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
